/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "check_vector.check" instead.
 */

#include <check.h>

#line 1 "check_vector.check"
#include <math.h>
#include "../src/vector/vector.h"
#define EPSILON .001

START_TEST(vector_mean)
{
#line 6
    int const vector[] = {8, 65, 96, 46, 61, 22, 40, 3, 13, 56, 81, 85, 30, 95, 62, 42};
    
    size_t const size = sizeof(vector) / sizeof(int);
    VECTOR_error_t err;

    fail_unless(fabs(VECTOR_mean(vector, size, &err) - 50.313) < EPSILON, "incorrect result");

}
END_TEST

START_TEST(vector_min_max)
{
#line 14
    int const vector[] = {8, 65, 96, 46, 61, 22, 40, 3, 13, 56, 81, 85, 30, 95, 62, 42};
    
    size_t const size = sizeof(vector) / sizeof(int);
    VECTOR_error_t err;

    VECTOR_int_pair_t const result = VECTOR_min_max(vector, size, &err);

    fail_unless(result.first == 3 && result.second == 96, "incorrect result");
    
}
END_TEST

START_TEST(vector_scalar_multiplication)
{
#line 24
    int const vector[] = {8, 65, 96, 46};
    size_t const size = sizeof(vector) / sizeof(int);
    double const d = 1.5;
    VECTOR_error_t err;

    double const* result = VECTOR_scalar_multiplication(vector, size, d, &err);

    fail_unless(fabs(result[0] - 12) < EPSILON, "incorrect result");
    fail_unless(fabs(result[1] - 97.5) < EPSILON, "incorrect result");
    fail_unless(fabs(result[2] - 144) < EPSILON, "incorrect result");
    fail_unless(fabs(result[3] - 69) < EPSILON, "incorrect result");
    
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, vector_mean);
    tcase_add_test(tc1_1, vector_min_max);
    tcase_add_test(tc1_1, vector_scalar_multiplication);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
