/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <pthread.h>

#include "calc.h"


void
calc_prog_1(char *host)
{
	CLIENT *clnt;
	output_mean  *result_1;
	input_vector  mean_1_arg;
	output_min_max  *result_2;
	input_vector  min_max_1_arg;
	output_scalar_multiplication  *result_3;
	input_scalar_multiplication  scalar_multiplication_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = mean_1(&mean_1_arg, clnt);
	if (result_1 == (output_mean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = min_max_1(&min_max_1_arg, clnt);
	if (result_2 == (output_min_max *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = scalar_multiplication_1(&scalar_multiplication_1_arg, clnt);
	if (result_3 == (output_scalar_multiplication *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host);
exit (0);
}
