/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calc.h"
#include "../vector/vector.h"
#include "../vector/error.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

output_mean *
mean_1(input_vector *argp, CLIENT *clnt)
{
	static output_mean clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MEAN,
		(xdrproc_t) xdr_input_vector, (caddr_t) argp,
		(xdrproc_t) xdr_output_mean, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

output_min_max *
min_max_1(input_vector *argp, CLIENT *clnt)
{
	static output_min_max clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MIN_MAX,
		(xdrproc_t) xdr_input_vector, (caddr_t) argp,
		(xdrproc_t) xdr_output_min_max, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

output_scalar_multiplication *
scalar_multiplication_1(input_scalar_multiplication *argp, CLIENT *clnt)
{
	static output_scalar_multiplication clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SCALAR_MULTIPLICATION,
		(xdrproc_t) xdr_input_scalar_multiplication, (caddr_t) argp,
		(xdrproc_t) xdr_output_scalar_multiplication, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
