/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include "../vector/vector.h"
#include "../vector/error.h"

static void
calc_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		input_vector mean_1_arg;
		input_vector min_max_1_arg;
		input_scalar_multiplication scalar_multiplication_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MEAN:
		_xdr_argument = (xdrproc_t) xdr_input_vector;
		_xdr_result = (xdrproc_t) xdr_output_mean;
		local = (char *(*)(char *, struct svc_req *)) mean_1_svc;
		break;

	case MIN_MAX:
		_xdr_argument = (xdrproc_t) xdr_input_vector;
		_xdr_result = (xdrproc_t) xdr_output_min_max;
		local = (char *(*)(char *, struct svc_req *)) min_max_1_svc;
		break;

	case SCALAR_MULTIPLICATION:
		_xdr_argument = (xdrproc_t) xdr_input_scalar_multiplication;
		_xdr_result = (xdrproc_t) xdr_output_scalar_multiplication;
		local = (char *(*)(char *, struct svc_req *)) scalar_multiplication_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALC_PROG, CALC_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALC_PROG, CALC_VERS, calc_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALC_PROG, CALC_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALC_PROG, CALC_VERS, calc_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALC_PROG, CALC_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
