/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include "../vector/vector.h"
#include "../vector/error.h"

struct input_vector {
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct input_vector input_vector;

struct output_mean {
	double mean;
	VECTOR_error_t err;
};
typedef struct output_mean output_mean;

struct output_min_max {
	VECTOR_int_pair_t pair;
	VECTOR_error_t err;
};
typedef struct output_min_max output_min_max;

struct input_scalar_multiplication {
	double a;
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct input_scalar_multiplication input_scalar_multiplication;

struct output_scalar_multiplication {
	struct {
		u_int y_len;
		double *y_val;
	} y;
	VECTOR_error_t err;
};
typedef struct output_scalar_multiplication output_scalar_multiplication;

#define CALC_PROG 0x23451111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MEAN 1
extern  output_mean * mean_1(input_vector *, CLIENT *);
extern  output_mean * mean_1_svc(input_vector *, struct svc_req *);
#define MIN_MAX 2
extern  output_min_max * min_max_1(input_vector *, CLIENT *);
extern  output_min_max * min_max_1_svc(input_vector *, struct svc_req *);
#define SCALAR_MULTIPLICATION 3
extern  output_scalar_multiplication * scalar_multiplication_1(input_scalar_multiplication *, CLIENT *);
extern  output_scalar_multiplication * scalar_multiplication_1_svc(input_scalar_multiplication *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MEAN 1
extern  output_mean * mean_1();
extern  output_mean * mean_1_svc();
#define MIN_MAX 2
extern  output_min_max * min_max_1();
extern  output_min_max * min_max_1_svc();
#define SCALAR_MULTIPLICATION 3
extern  output_scalar_multiplication * scalar_multiplication_1();
extern  output_scalar_multiplication * scalar_multiplication_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_vector (XDR *, input_vector*);
extern  bool_t xdr_output_mean (XDR *, output_mean*);
extern  bool_t xdr_output_min_max (XDR *, output_min_max*);
extern  bool_t xdr_input_scalar_multiplication (XDR *, input_scalar_multiplication*);
extern  bool_t xdr_output_scalar_multiplication (XDR *, output_scalar_multiplication*);

#else /* K&R C */
extern bool_t xdr_input_vector ();
extern bool_t xdr_output_mean ();
extern bool_t xdr_output_min_max ();
extern bool_t xdr_input_scalar_multiplication ();
extern bool_t xdr_output_scalar_multiplication ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
