/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

output_mean *
mean_1_svc(input_vector *argp, struct svc_req *rqstp)
{
	static output_mean  result;

	result.mean = VECTOR_mean(argp->y.y_val, argp->y.y_len, &result.err);

	return &result;
}

output_min_max *
min_max_1_svc(input_vector *argp, struct svc_req *rqstp)
{
	static output_min_max  result;

	result.pair = VECTOR_min_max(argp->y.y_val, argp->y.y_len, &result.err);

	return &result;
}

output_scalar_multiplication *
scalar_multiplication_1_svc(input_scalar_multiplication *argp, struct svc_req *rqstp)
{
	static output_scalar_multiplication  result;

	result.y.y_val = VECTOR_scalar_multiplication(argp->y.y_val, argp->y.y_len, argp->a, 
		&result.err);
	result.y.y_len = argp->y.y_len;

	return &result;
}
