/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_input_vector (XDR *xdrs, input_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_mean (XDR *xdrs, output_mean *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->mean))
		 return FALSE;
	 if (!xdr_VECTOR_error_t (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_min_max (XDR *xdrs, output_min_max *objp)
{
	register int32_t *buf;

	 if (!xdr_VECTOR_int_pair_t (xdrs, &objp->pair))
		 return FALSE;
	 if (!xdr_VECTOR_error_t (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_scalar_multiplication (XDR *xdrs, input_scalar_multiplication *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_scalar_multiplication (XDR *xdrs, output_scalar_multiplication *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_VECTOR_error_t (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}
